In [46]:
import pandas as pd

In [47]:
food = pd.read_csv("Data/year_msoa_grocery.csv")
food.head()

,area_id,weight,weight_perc2.5,weight_perc25,weight_perc50,weight_perc75,weight_perc97.5,weight_std,weight_ci95,volume,...,man_day,population,male,female,age_0_17,age_18_64,age_65+,avg_age,area_sq_km,people_per_sq_km
0,E02000001,323.180804,35.0,150.0,250.0,400.0,1000.0,323.685705,1.001360,98.849228,...,103934,6687.0,3697.0,2990.0,1018.0,4349.0,1320.0,43.910124,2.90,2305.862069
1,E02000002,397.651232,32.5,150.0,300.0,500.0,1020.0,550.434424,6.030232,118.288417,...,9952,7379.0,3549.0,3830.0,2150.0,4151.0,1078.0,35.567286,2.16,3416.203704
2,E02000003,371.276702,30.0,140.0,250.0,450.0,1200.0,564.404826,4.398728,118.385615,...,19576,10720.0,5297.0,5423.0,2762.0,6649.0,1309.0,35.700466,2.14,5009.345794
3,E02000004,347.481292,29.0,126.0,250.0,430.0,1000.0,479.372575,5.297349,104.435407,...,10689,6536.0,3119.0,3417.0,1454.0,4044.0,1038.0,38.493115,2.48,2635.483871
4,E02000005,400.576688,32.5,150.0,296.0,500.0,1050.0,593.021809,5.107669,128.997438,...,15071,9243.0,4478.0,4765.0,2678.0,5554.0,1011.0,34.156335,1.19,7767.226891

In [48]:
deaths = pd.read_csv("Data/coviddeaths.csv")
deaths.head()

   MSOA code  March  April  May  June  July  Covid Deaths March to July
0  E02000001      1      2    1     0     0                           4
1  E02000002      1      7    0     0     0                           8
2  E02000003      1      7    2     0     0                          10
3  E02000004      6      6    1     1     0                          14
4  E02000005      4      2    1     0     0                           7

In [49]:
imd = pd.read_csv("Data/imd2019_msoa_level_data.csv")
imd.head()

       MSOAC  LSOACOUNT  POPMID15  IMD19 SCORE
0  E02000001          6      6687    14.720484
1  E02000002          4      7379    34.767560
2  E02000003          6     10720    25.149726
3  E02000004          4      6536    23.560044
4  E02000005          5      9243    30.212965

In [50]:
merged = imd.merge(deaths, left_on="MSOAC", right_on="MSOA code").drop("MSOA code",axis=1)
merged = merged.merge(food, left_on="MSOAC", right_on="area_id").drop(["March","April","May","June","July","LSOACOUNT","POPMID15"], axis=1)
merged = merged.merge(food, left_on="MSOAC", right_on="area_id")
merged.head()

,MSOAC,IMD19 SCORE,Covid Deaths March to July,area_id_x,weight_x,weight_perc2.5_x,weight_perc25_x,weight_perc50_x,weight_perc75_x,weight_perc97.5_x,...,man_day_y,population_y,male_y,female_y,age_0_17_y,age_18_64_y,age_65+_y,avg_age_y,area_sq_km_y,people_per_sq_km_y
0,E02000001,14.720484,4,E02000001,323.180804,35.0,150.0,250.0,400.0,1000.0,...,103934,6687.0,3697.0,2990.0,1018.0,4349.0,1320.0,43.910124,2.90,2305.862069
1,E02000002,34.767560,8,E02000002,397.651232,32.5,150.0,300.0,500.0,1020.0,...,9952,7379.0,3549.0,3830.0,2150.0,4151.0,1078.0,35.567286,2.16,3416.203704
2,E02000003,25.149726,10,E02000003,371.276702,30.0,140.0,250.0,450.0,1200.0,...,19576,10720.0,5297.0,5423.0,2762.0,6649.0,1309.0,35.700466,2.14,5009.345794
3,E02000004,23.560044,14,E02000004,347.481292,29.0,126.0,250.0,430.0,1000.0,...,10689,6536.0,3119.0,3417.0,1454.0,4044.0,1038.0,38.493115,2.48,2635.483871
4,E02000005,30.212965,7,E02000005,400.576688,32.5,150.0,296.0,500.0,1050.0,...,15071,9243.0,4478.0,4765.0,2678.0,5554.0,1011.0,34.156335,1.19,7767.226891

In [52]:
for cols in merged.columns:
    print(cols)

MSOAC
IMD19 SCORE
Covid Deaths March to July
area_id_x
weight_x
weight_perc2.5_x
weight_perc25_x
weight_perc50_x
weight_perc75_x
weight_perc97.5_x
weight_std_x
weight_ci95_x
volume_x
volume_perc2.5_x
volume_perc25_x
volume_perc50_x
volume_perc75_x
volume_perc97.5_x
volume_std_x
volume_ci95_x
fat_x
fat_perc2.5_x
fat_perc25_x
fat_perc50_x
fat_perc75_x
fat_perc97.5_x
fat_std_x
fat_ci95_x
saturate_x
saturate_perc2.5_x
saturate_perc25_x
saturate_perc50_x
saturate_perc75_x
saturate_perc97.5_x
saturate_std_x
saturate_ci95_x
salt_x
salt_perc2.5_x
salt_perc25_x
salt_perc50_x
salt_perc75_x
salt_perc97.5_x
salt_std_x
salt_ci95_x
sugar_x
sugar_perc2.5_x
sugar_perc25_x
sugar_perc50_x
sugar_perc75_x
sugar_perc97.5_x
sugar_std_x
sugar_ci95_x
protein_x
protein_perc2.5_x
protein_perc25_x
protein_perc50_x
protein_perc75_x
protein_perc97.5_x
protein_std_x
protein_ci95_x
carb_x
carb_perc2.5_x
carb_perc25_x
carb_perc50_x
carb_perc75_x
carb_perc97.5_x
carb_std_x
carb_ci95_x
fibre_x
fibre_perc2.5_x
fibre_perc25_x
fibre_perc50_x
fibre_perc75_x
fibre_perc97.5_x
fibre_std_x
fibre_ci95_x
alcohol_x
alcohol_perc2.5_x
alcohol_perc25_x
alcohol_perc50_x
alcohol_perc75_x
alcohol_perc97.5_x
alcohol_std_x
alcohol_ci95_x
energy_fat_x
energy_fat_perc2.5_x
energy_fat_perc25_x
energy_fat_perc50_x
energy_fat_perc75_x
energy_fat_perc97.5_x
energy_fat_std_x
energy_fat_ci95_x
energy_saturate_x
energy_saturate_perc2.5_x
energy_saturate_perc25_x
energy_saturate_perc50_x
energy_saturate_perc75_x
energy_saturate_perc97.5_x
energy_saturate_std_x
energy_saturate_ci95_x
energy_sugar_x
energy_sugar_perc2.5_x
energy_sugar_perc25_x
energy_sugar_perc50_x
energy_sugar_perc75_x
energy_sugar_perc97.5_x
energy_sugar_std_x
energy_sugar_ci95_x
energy_protein_x
energy_protein_perc2.5_x
energy_protein_perc25_x
energy_protein_perc50_x
energy_protein_perc75_x
energy_protein_perc97.5_x
energy_protein_std_x
energy_protein_ci95_x
energy_carb_x
energy_carb_perc2.5_x
energy_carb_perc25_x
energy_carb_perc50_x
energy_carb_perc75_x
energy_carb_perc97.5_x
energy_carb_std_x
energy_carb_ci95_x
energy_fibre_x
energy_fibre_perc2.5_x
energy_fibre_perc25_x
energy_fibre_perc50_x
energy_fibre_perc75_x
energy_fibre_perc97.5_x
energy_fibre_std_x
energy_fibre_ci95_x
energy_alcohol_x
energy_alcohol_perc2.5_x
energy_alcohol_perc25_x
energy_alcohol_perc50_x
energy_alcohol_perc75_x
energy_alcohol_perc97.5_x
energy_alcohol_std_x
energy_alcohol_ci95_x
energy_tot_x
energy_tot_perc2.5_x
energy_tot_perc25_x
energy_tot_perc50_x
energy_tot_perc75_x
energy_tot_perc97.5_x
energy_tot_std_x
energy_tot_ci95_x
f_energy_fat_x
f_energy_saturate_x
f_energy_sugar_x
f_energy_protein_x
f_energy_carb_x
f_energy_fibre_x
f_energy_alcohol_x
energy_density_x
h_nutrients_weight_x
h_nutrients_weight_norm_x
h_nutrients_calories_x
h_nutrients_calories_norm_x
f_beer_x
f_dairy_x
f_eggs_x
f_fats_oils_x
f_fish_x
f_fruit_veg_x
f_grains_x
f_meat_red_x
f_poultry_x
f_readymade_x
f_sauces_x
f_soft_drinks_x
f_spirits_x
f_sweets_x
f_tea_coffee_x
f_water_x
f_wine_x
f_dairy_weight_x
f_eggs_weight_x
f_fats_oils_weight_x
f_fish_weight_x
f_fruit_veg_weight_x
f_grains_weight_x
f_meat_red_weight_x
f_poultry_weight_x
f_readymade_weight_x
f_sauces_weight_x
f_sweets_weight_x
h_items_x
h_items_norm_x
h_items_weight_x
h_items_weight_norm_x
representativeness_norm_x
transaction_days_x
num_transactions_x
man_day_x
population_x
male_x
female_x
age_0_17_x
age_18_64_x
age_65+_x
avg_age_x
area_sq_km_x
people_per_sq_km_x
area_id_y
weight_y
weight_perc2.5_y
weight_perc25_y
weight_perc50_y
weight_perc75_y
weight_perc97.5_y
weight_std_y
weight_ci95_y
volume_y
volume_perc2.5_y
volume_perc25_y
volume_perc50_y
volume_perc75_y
volume_perc97.5_y
volume_std_y
volume_ci95_y
fat_y
fat_perc2.5_y
fat_perc25_y
fat_perc50_y
fat_perc75_y
fat_perc97.5_y
fat_std_y
fat_ci95_y
saturate_y
saturate_perc2.5_y
saturate_perc25_y
saturate_perc50_y
saturate_perc75_y
saturate_perc97.5_y
saturate_std_y
saturate_ci95_y
salt_y
salt_perc2.5_y
salt_perc25_y
salt_perc50_y
salt_perc75_y
salt_perc97.5_y
salt_std_y
salt_ci95_y
sugar_y
sugar_perc2.5_y
sugar_perc25_y
sugar_perc50_y
sugar_perc75_y
sugar_perc97.5_y
sugar_std_y
sugar_ci95_y
protein_y
protein_perc2.5_y
protein_perc25_y
protein_perc50_y
protein_perc75_y
protein_perc97.5_y
protein_std_y
protein_ci95_y
carb_y
carb_perc2.5_y
carb_perc25_y
carb_perc50_y
carb_perc75_y
carb_perc97.5_y
carb_std_y
carb_ci95_y
fibre_y
fibre_perc2.5_y
fibre_perc25_y
fibre_perc50_y
fibre_perc75_y
fibre_perc97.5_y
fibre_std_y
fibre_ci95_y
alcohol_y
alcohol_perc2.5_y
alcohol_perc25_y
alcohol_perc50_y
alcohol_perc75_y
alcohol_perc97.5_y
alcohol_std_y
alcohol_ci95_y
energy_fat_y
energy_fat_perc2.5_y
energy_fat_perc25_y
energy_fat_perc50_y
energy_fat_perc75_y
energy_fat_perc97.5_y
energy_fat_std_y
energy_fat_ci95_y
energy_saturate_y
energy_saturate_perc2.5_y
energy_saturate_perc25_y
energy_saturate_perc50_y
energy_saturate_perc75_y
energy_saturate_perc97.5_y
energy_saturate_std_y
energy_saturate_ci95_y
energy_sugar_y
energy_sugar_perc2.5_y
energy_sugar_perc25_y
energy_sugar_perc50_y
energy_sugar_perc75_y
energy_sugar_perc97.5_y
energy_sugar_std_y
energy_sugar_ci95_y
energy_protein_y
energy_protein_perc2.5_y
energy_protein_perc25_y
energy_protein_perc50_y
energy_protein_perc75_y
energy_protein_perc97.5_y
energy_protein_std_y
energy_protein_ci95_y
energy_carb_y
energy_carb_perc2.5_y
energy_carb_perc25_y
energy_carb_perc50_y
energy_carb_perc75_y
energy_carb_perc97.5_y
energy_carb_std_y
energy_carb_ci95_y
energy_fibre_y
energy_fibre_perc2.5_y
energy_fibre_perc25_y
energy_fibre_perc50_y
energy_fibre_perc75_y
energy_fibre_perc97.5_y
energy_fibre_std_y
energy_fibre_ci95_y
energy_alcohol_y
energy_alcohol_perc2.5_y
energy_alcohol_perc25_y
energy_alcohol_perc50_y
energy_alcohol_perc75_y
energy_alcohol_perc97.5_y
energy_alcohol_std_y
energy_alcohol_ci95_y
energy_tot_y
energy_tot_perc2.5_y
energy_tot_perc25_y
energy_tot_perc50_y
energy_tot_perc75_y
energy_tot_perc97.5_y
energy_tot_std_y
energy_tot_ci95_y
f_energy_fat_y
f_energy_saturate_y
f_energy_sugar_y
f_energy_protein_y
f_energy_carb_y
f_energy_fibre_y
f_energy_alcohol_y
energy_density_y
h_nutrients_weight_y
h_nutrients_weight_norm_y
h_nutrients_calories_y
h_nutrients_calories_norm_y
f_beer_y
f_dairy_y
f_eggs_y
f_fats_oils_y
f_fish_y
f_fruit_veg_y
f_grains_y
f_meat_red_y
f_poultry_y
f_readymade_y
f_sauces_y
f_soft_drinks_y
f_spirits_y
f_sweets_y
f_tea_coffee_y
f_water_y
f_wine_y
f_dairy_weight_y
f_eggs_weight_y
f_fats_oils_weight_y
f_fish_weight_y
f_fruit_veg_weight_y
f_grains_weight_y
f_meat_red_weight_y
f_poultry_weight_y
f_readymade_weight_y
f_sauces_weight_y
f_sweets_weight_y
h_items_y
h_items_norm_y
h_items_weight_y
h_items_weight_norm_y
representativeness_norm_y
transaction_days_y
num_transactions_y
man_day_y
population_y
male_y
female_y
age_0_17_y
age_18_64_y
age_65+_y
avg_age_y
area_sq_km_y
people_per_sq_km_y